service: release-web-app-bot
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  stackName: release-web-app-bot
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
functions:
  slack:
    handler: app.handler
    events:
      - http: ANY /
      - http:
          path: '{proxy+}'
          method: any
plugins:
  - serverless-offline